volumes:
  ingestion-volume-dag-airflow:
  ingestion-volume-dags:
  ingestion-volume-tmp:
  es-data:
  om-db-data:

services:
  om-postgresql:
    container_name: openmetadata_postgresql
    image: docker.getcollate.io/openmetadata/postgresql:1.6.2
    restart: always
    command: "--work_mem=10MB"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    expose:
      - 5432
    ports:
      - "5433:5432"
    volumes:
      - om-db-data:/var/lib/postgresql/data
    networks:
      - om_net
    healthcheck:
      test: psql -U postgres -tAc 'select 1' -d openmetadata_db
      interval: 15s
      timeout: 10s
      retries: 10

  elasticsearch:
    container_name: openmetadata_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    networks:
      - om_net
    ports:
      - "9200:9200"
    healthcheck:
      test: "curl -s http://localhost:9200/_cluster/health?pretty | grep status | grep -qE 'green|yellow' || exit 1"
      interval: 15s
      timeout: 10s
      retries: 10
    volumes:
      - es-data:/usr/share/elasticsearch/data

  execute-migrate-all:
    container_name: execute_migrate_all
    image: docker.getcollate.io/openmetadata/server:1.6.2
    command: "./bootstrap/openmetadata-ops.sh migrate"
    environment:
      OPENMETADATA_CLUSTER_NAME: openmetadata
      SERVER_PORT: 8585
      SERVER_ADMIN_PORT: 8586
      LOG_LEVEL: INFO
      MIGRATION_LIMIT_PARAM: 1200
      AUTHORIZER_CLASS_NAME: org.openmetadata.service.security.DefaultAuthorizer
      AUTHORIZER_REQUEST_FILTER: org.openmetadata.service.security.JwtFilter
      AUTHORIZER_ADMIN_PRINCIPALS: "[admin]"
      AUTHORIZER_ALLOWED_REGISTRATION_DOMAIN: '["all"]'
      AUTHORIZER_INGESTION_PRINCIPALS: "[ingestion-bot]"
      AUTHORIZER_PRINCIPAL_DOMAIN: "open-metadata.org"
      AUTHORIZER_ENFORCE_PRINCIPAL_DOMAIN: "false"
      AUTHENTICATION_PROVIDER: basic
      AUTHENTICATION_PUBLIC_KEYS: "[http://localhost:8585/api/v1/system/config/jwks]"
      AUTHENTICATION_AUTHORITY: "https://accounts.google.com"
      AUTHENTICATION_ENABLE_SELF_SIGNUP: "true"
      AUTHENTICATION_CLIENT_TYPE: public
      RSA_PUBLIC_KEY_FILE_PATH: "./conf/public_key.der"
      RSA_PRIVATE_KEY_FILE_PATH: "./conf/private_key.der"
      JWT_ISSUER: "open-metadata.org"
      JWT_KEY_ID: "Gb389a-9f76-gdjs-a92j-0242bk94356"
      PIPELINE_SERVICE_CLIENT_ENDPOINT: http://ingestion:8080
      SERVER_HOST_API_URL: http://openmetadata-server:8585/api
      DB_DRIVER_CLASS: org.postgresql.Driver
      DB_SCHEME: postgresql
      DB_PARAMS: "allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
      DB_USER: openmetadata_user
      DB_USER_PASSWORD: openmetadata_password
      DB_HOST: om-postgresql
      DB_PORT: 5432
      OM_DATABASE: openmetadata_db
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      ELASTICSEARCH_SCHEME: http
      SEARCH_TYPE: elasticsearch
      ELASTICSEARCH_BATCH_SIZE: 100
      ELASTICSEARCH_INDEX_MAPPING_LANG: EN
      PIPELINE_SERVICE_CLIENT_CLASS_NAME: "org.openmetadata.service.clients.pipeline.airflow.AirflowRESTClient"
      AIRFLOW_USERNAME: admin
      AIRFLOW_PASSWORD: admin
      FERNET_KEY: "jJ/9sz0g0OHxsfxOoSfdFdmk3ysNmPRnH3TUAbz3IHA="
      SECRET_MANAGER: db
      OPENMETADATA_HEAP_OPTS: "-Xmx1G -Xms1G"
    depends_on:
      elasticsearch:
        condition: service_healthy
      om-postgresql:
        condition: service_healthy
    networks:
      - om_net

  openmetadata-server:
    container_name: openmetadata_server
    restart: always
    image: docker.getcollate.io/openmetadata/server:1.6.2
    environment:
      OPENMETADATA_CLUSTER_NAME: openmetadata
      SERVER_PORT: 8585
      SERVER_ADMIN_PORT: 8586
      LOG_LEVEL: INFO
      AUTHORIZER_CLASS_NAME: org.openmetadata.service.security.DefaultAuthorizer
      AUTHORIZER_REQUEST_FILTER: org.openmetadata.service.security.JwtFilter
      AUTHORIZER_ADMIN_PRINCIPALS: "[admin]"
      AUTHORIZER_ALLOWED_REGISTRATION_DOMAIN: '["all"]'
      AUTHORIZER_INGESTION_PRINCIPALS: "[ingestion-bot]"
      AUTHORIZER_PRINCIPAL_DOMAIN: "open-metadata.org"
      AUTHORIZER_ENFORCE_PRINCIPAL_DOMAIN: "false"
      AUTHENTICATION_PROVIDER: basic
      AUTHENTICATION_PUBLIC_KEYS: "[http://localhost:8585/api/v1/system/config/jwks]"
      AUTHENTICATION_AUTHORITY: "https://accounts.google.com"
      AUTHENTICATION_ENABLE_SELF_SIGNUP: "true"
      AUTHENTICATION_CLIENT_TYPE: public
      RSA_PUBLIC_KEY_FILE_PATH: "./conf/public_key.der"
      RSA_PRIVATE_KEY_FILE_PATH: "./conf/private_key.der"
      JWT_ISSUER: "open-metadata.org"
      JWT_KEY_ID: "Gb389a-9f76-gdjs-a92j-0242bk94356"
      PIPELINE_SERVICE_CLIENT_ENDPOINT: http://ingestion:8080
      SERVER_HOST_API_URL: http://openmetadata-server:8585/api
      DB_DRIVER_CLASS: org.postgresql.Driver
      DB_SCHEME: postgresql
      DB_PARAMS: "allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
      DB_USER: openmetadata_user
      DB_USER_PASSWORD: openmetadata_password
      DB_HOST: om-postgresql
      DB_PORT: 5432
      OM_DATABASE: openmetadata_db
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      ELASTICSEARCH_SCHEME: http
      SEARCH_TYPE: elasticsearch
      ELASTICSEARCH_BATCH_SIZE: 100
      ELASTICSEARCH_INDEX_MAPPING_LANG: EN
      PIPELINE_SERVICE_CLIENT_CLASS_NAME: "org.openmetadata.service.clients.pipeline.airflow.AirflowRESTClient"
      AIRFLOW_USERNAME: admin
      AIRFLOW_PASSWORD: admin
      FERNET_KEY: "jJ/9sz0g0OHxsfxOoSfdFdmk3ysNmPRnH3TUAbz3IHA="
      SECRET_MANAGER: db
      OPENMETADATA_HEAP_OPTS: "-Xmx1G -Xms1G"
      MASK_PASSWORDS_API: "false"
    expose:
      - 8585
      - 8586
    ports:
      - "8585:8585"
      - "8586:8586"
    depends_on:
      elasticsearch:
        condition: service_healthy
      om-postgresql:
        condition: service_healthy
      execute-migrate-all:
        condition: service_completed_successfully
    networks:
      - om_net
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8586/healthcheck"]

  ingestion:
    container_name: openmetadata_ingestion
    image: docker.getcollate.io/openmetadata/ingestion:1.6.2
    depends_on:
      elasticsearch:
        condition: service_started
      om-postgresql:
        condition: service_healthy
      openmetadata-server:
        condition: service_started
    environment:
      AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__OPENMETADATA_AIRFLOW_APIS__DAG_GENERATED_CONFIGS: "/opt/airflow/dag_generated_configs"
      DB_HOST: om-postgresql
      DB_PORT: 5432
      AIRFLOW_DB: airflow_db
      DB_USER: airflow_user
      DB_SCHEME: "postgresql+psycopg2"
      DB_PASSWORD: airflow_pass
    entrypoint: /bin/bash
    command:
      - "/opt/airflow/ingestion_dependency.sh"
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - om_net
    volumes:
      - ingestion-volume-dag-airflow:/opt/airflow/dag_generated_configs
      - ingestion-volume-dags:/opt/airflow/dags
      - ingestion-volume-tmp:/tmp

networks:
  om_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.240.0/24"
