"""
Amazon Redshift Target Adapter (AWS)

Implements the BaseTargetAdapter interface for Amazon Redshift, providing type
mapping, function translation, and DDL generation.
"""

import logging
from datetime import datetime, timezone
from typing import Dict, List, Optional

from dm.targets.base import BaseTargetAdapter

logger = logging.getLogger(__name__)

TYPE_MAP = {
    # Integer types
    "integer": "INTEGER",
    "int": "INTEGER",
    "bigint": "BIGINT",
    "smallint": "SMALLINT",
    "tinyint": "SMALLINT",
    "serial": "INTEGER IDENTITY(1,1)",
    # Numeric types
    "numeric": "DECIMAL",
    "decimal": "DECIMAL",
    "real": "REAL",
    "double precision": "DOUBLE PRECISION",
    "double": "DOUBLE PRECISION",
    "float": "DOUBLE PRECISION",
    # String types
    "character varying": "VARCHAR",
    "varchar": "VARCHAR",
    "varchar2": "VARCHAR",
    "nvarchar": "VARCHAR",
    "nvarchar2": "VARCHAR",
    "character": "CHAR",
    "char": "CHAR",
    "nchar": "CHAR",
    "text": "VARCHAR(65535)",
    "clob": "VARCHAR(65535)",
    "nclob": "VARCHAR(65535)",
    "long": "VARCHAR(65535)",
    # Boolean
    "boolean": "BOOLEAN",
    "bool": "BOOLEAN",
    # Date / Time
    "date": "DATE",
    "timestamp without time zone": "TIMESTAMP",
    "timestamp with time zone": "TIMESTAMPTZ",
    "timestamp": "TIMESTAMPTZ",
    "timestamptz": "TIMESTAMPTZ",
    "time": "TIMESTAMP",
    "time with time zone": "TIMESTAMPTZ",
    "interval": "VARCHAR(50)",
    # Binary — Redshift has no native binary type
    "bytea": "VARCHAR(65535)",
    "blob": "VARCHAR(65535)",
    "raw": "VARCHAR(65535)",
    "long raw": "VARCHAR(65535)",
    # UUID / JSON — Redshift supports SUPER for semi-structured data
    "uuid": "VARCHAR(36)",
    "json": "SUPER",
    "jsonb": "SUPER",
    # Oracle / mainframe legacy types
    "number": "DECIMAL",
    "string": "VARCHAR",
    "binary_float": "REAL",
    "binary_double": "DOUBLE PRECISION",
    "rowid": "VARCHAR(18)",
}

FUNCTION_MAP = {
    "nvl":       lambda args: f"NVL({', '.join(args)})",
    "nvl2":      lambda args: f"NVL2({', '.join(args)})" if len(args) >= 3 else f"NVL({', '.join(args)})",
    "coalesce":  lambda args: f"COALESCE({', '.join(args)})",
    "sysdate":   lambda args: "GETDATE()",
    "systimestamp": lambda args: "GETDATE()",
    "getdate":   lambda args: "GETDATE()",
    "now":       lambda args: "GETDATE()",
    "decode":    lambda args: f"DECODE({', '.join(args)})" if args else "NULL",
    "to_date":   lambda args: f"TO_DATE({', '.join(args)}, 'YYYY-MM-DD')" if len(args) == 1 else f"TO_DATE({', '.join(args)})",
    "to_char":   lambda args: f"TO_CHAR({', '.join(args)})",
    "to_number": lambda args: f"({args[0]})::DECIMAL" if args else "0",
    "instr":     lambda args: f"CHARINDEX({args[1]}, {args[0]})" if len(args) >= 2 else "0",
    "substr":    lambda args: f"SUBSTRING({', '.join(args)})",
    "length":    lambda args: f"LEN({args[0]})" if args else "LEN('')",
    "concat":    lambda args: " || ".join(args) if args else "''",
    "ifnull":    lambda args: f"NVL({', '.join(args)})",
    "isnull":    lambda args: f"NVL({', '.join(args)})",
    "charindex": lambda args: f"CHARINDEX({', '.join(args)})",
    "dateadd":   lambda args: f"DATEADD({', '.join(args)})" if len(args) >= 3 else "GETDATE()",
    "datediff":  lambda args: f"DATEDIFF({', '.join(args)})" if len(args) >= 3 else "0",
    "user":      lambda args: "CURRENT_USER",
    "rownum":    lambda args: "ROW_NUMBER() OVER ()",
}


class RedshiftTargetAdapter(BaseTargetAdapter):
    """Amazon Redshift (AWS) target platform adapter."""

    def dialect_name(self) -> str:
        return "redshift"

    def map_type(self, source_type: str, profiling_stats: Optional[dict] = None) -> str:
        import re
        raw = source_type.strip()
        raw = re.split(r'\s+(?:PRIMARY|NOT|DEFAULT|UNIQUE|CHECK|REFERENCES|GENERATED)\b', raw, flags=re.IGNORECASE)[0].strip()
        base = raw.lower().split("(")[0].strip()
        size_match = re.search(r"\(([^)]+)\)", raw)
        size_qualifier = size_match.group(1) if size_match else None

        rs_type = TYPE_MAP.get(base)
        if rs_type is None:
            logger.warning(f"Unmapped source type '{source_type}', defaulting to VARCHAR")
            rs_type = "VARCHAR"

        if size_qualifier and rs_type in ("VARCHAR", "CHAR", "DECIMAL"):
            return f"{rs_type}({size_qualifier})"
        return rs_type

    def render_create_table(
        self,
        table_name: str,
        columns: List[Dict],
        primary_key: str,
        foreign_keys: List[Dict] = None,
        comment: str = "",
    ) -> str:
        foreign_keys = foreign_keys or []
        lines = [
            f"-- Generated by DM Target Adapter (redshift / AWS)",
            f"-- Generated: {datetime.now(timezone.utc).isoformat()}",
            "",
            f"CREATE TABLE {table_name} (",
        ]

        col_defs = []
        for col in columns:
            name = col["name"]
            data_type = col["data_type"]
            nullable = col.get("nullable", True)
            constraints = col.get("constraints", [])

            parts = [f"    {name:<25} {data_type}"]

            for c in constraints:
                # Redshift supports PK/UNIQUE as hints (not enforced) and CHECK
                if not c.startswith("REFERENCES"):
                    parts.append(f" {c}")

            if not nullable and "NOT NULL" not in constraints and "PRIMARY KEY" not in constraints:
                parts.append(" NOT NULL")

            col_comment = col.get("comment", "")
            if col_comment:
                parts.append(f"  -- {col_comment}")

            col_defs.append("".join(parts))

        lines.append(",\n".join(col_defs))
        lines.append(")")

        # Redshift table properties: distribution and sort keys
        # Default to distribution on the PK for even data spread
        if primary_key:
            lines.append(f"DISTSTYLE KEY")
            lines.append(f"DISTKEY ({primary_key})")
            lines.append(f"SORTKEY ({primary_key})")

        lines.append(";")

        # Redshift uses COMMENT via ALTER TABLE
        if comment:
            escaped = comment.replace("'", "''")
            lines.append(f"\nCOMMENT ON TABLE {table_name} IS '{escaped}';")

        for col in columns:
            col_comment = col.get("comment", "")
            if col_comment:
                escaped = col_comment.replace("'", "''")
                lines.append(
                    f"COMMENT ON COLUMN {table_name}.{col['name']} IS '{escaped}';"
                )

        lines.append("")
        return "\n".join(lines)

    def render_insert_select(
        self,
        target_table: str,
        source_table: str,
        column_mappings: List[Dict],
    ) -> str:
        if not column_mappings:
            return f"-- No column mappings for {target_table}\n"
        target_cols = [m["target_col"] for m in column_mappings]
        source_exprs = [m["source_expr"] for m in column_mappings]
        cols_str = ",\n    ".join(target_cols)
        exprs_str = ",\n    ".join(source_exprs)
        lines = [
            f"-- Migration: {source_table} -> {target_table}",
            "",
            f"INSERT INTO {target_table} (",
            f"    {cols_str}",
            f")",
            f"SELECT",
            f"    {exprs_str}",
            f"FROM {source_table};",
            "",
        ]
        return "\n".join(lines)

    def translate_function(self, func_name: str, args: list) -> str:
        key = func_name.lower().strip()
        translator = FUNCTION_MAP.get(key)
        if translator:
            return translator(args)
        args_str = ", ".join(args) if args else ""
        return f"{func_name}({args_str})"

    def supports_serial(self) -> bool:
        return True  # IDENTITY columns

    def supports_check_constraints(self) -> bool:
        return False  # Redshift doesn't enforce CHECK constraints
