-- Contact Management System — Modern Schema
-- PostgreSQL target with proper types, constraints, and naming

CREATE TABLE IF NOT EXISTS contacts (
    contact_id              INTEGER PRIMARY KEY,
    first_name              VARCHAR(50) NOT NULL,
    middle_name             VARCHAR(50),
    last_name               VARCHAR(50) NOT NULL,
    name_suffix             VARCHAR(10),
    ssn_hash                VARCHAR(64),
    date_of_birth           DATE,
    gender                  VARCHAR(1),
    ethnicity               VARCHAR(30),
    primary_phone           BIGINT,
    mobile_phone            BIGINT,
    work_phone              BIGINT,
    email                   VARCHAR(100),
    address_line1           VARCHAR(100),
    address_line2           VARCHAR(100),
    city                    VARCHAR(50),
    state                   VARCHAR(2),
    zip_code                VARCHAR(10),
    address_type            VARCHAR(10),
    mailing_address_line1   VARCHAR(100),
    mailing_address_line2   VARCHAR(100),
    mailing_city            VARCHAR(50),
    mailing_state           VARCHAR(2),
    mailing_zip_code        VARCHAR(10),
    emergency_contact_name  VARCHAR(100),
    emergency_contact_phone BIGINT,
    emergency_contact_relation VARCHAR(30),
    drivers_license_number  VARCHAR(30),
    drivers_license_state   VARCHAR(2),
    marital_status          VARCHAR(15),
    dependents_count        INTEGER DEFAULT 0,
    language_preference     VARCHAR(20),
    is_veteran              BOOLEAN DEFAULT FALSE,
    is_disabled             BOOLEAN DEFAULT FALSE,
    contact_status          VARCHAR(15) NOT NULL DEFAULT 'active',
    created_at              TIMESTAMPTZ DEFAULT NOW(),
    updated_at              TIMESTAMPTZ DEFAULT NOW(),
    source_code             VARCHAR(15)
);
